version: "3.7"

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - files
    ports:
      - "443:443"
    volumes:
      - ./nginx-myconf.conf:/etc/nginx/nginx.conf

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/app
    depends_on:
      - redis1

  files:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www/app
    depends_on:
      - redis2

  redis1:
    image: redis

  redis2:
    image: redis
