version: "3.7"

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - api
      - web
      - files
    ports:
      - "443:443"
    volumes:
      - ./nginx-myconf.conf:/etc/nginx/nginx.conf
      - ./cert.crt:/etc/nginx/server.company.com.crt

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web/app:/var/www/app
    depends_on:
      - redis1

  files:
    build:
      context: files
      dockerfile: Dockerfile
    volumes:
      - ./files:/var/www/app
    depends_on:
      - redis2

  api:
    build:
      context: API
      dockerfile: Dockerfile
    volumes:
      - ./API:/var/www/app
    depends_on:
      - redis3
    ports:
      - "5000:5000"

  redis1:
    image: redis

  redis2:
    image: redis

  redis3:
    image: redis