version: "3.7"

services:
  web:
    build: 
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    

  redis:
    build:
      context: redis_mine
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
  


