version: "3.7"

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - web
    ports:
      - "443:443"
    volumes:
      - ./nginx-myconf.conf:/etc/nginx/nginx.conf

  web:
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - ./web:/var/www/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
